import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Magic Orb',
  description: 'Generated by create next app',
}

export default function RootLayout({ children  }) {
  return (
    <html lang="en" >
      <body className={`${inter.className} 'bg-gradient-to-b from-[#442143] to-[#2B3057]'`} >{children}</body>
    </html>
  )
}
